When trying to get explorer info the backend is getting the error of AttributeError: Got AttributeError when attempting to get a value for field  on serializer . The serializer field might be named incorrectly and not match any attribute or key on the  instance. Original exception text was: 'QuerySet' object has no attribute 'first_name'... looking to what is causing this in order to resolve and provide the correct information to be displayed on the front end